# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mu Chen Studio
tagline:          'Happy hacking!'
description:      ''
url:              http://vanemu.com

author:
  name:           'Mu'
  url:            https://twitter.com/vanemu

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/vanemu
